// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCYumgWxFZiXIR0w-I0WSugPRL0jhb9uTQ',
    appId: '1:159878091400:web:90351c5b73f357357a053d',
    messagingSenderId: '159878091400',
    projectId: 'fir-auth1-79511',
    authDomain: 'fir-auth1-79511.firebaseapp.com',
    storageBucket: 'fir-auth1-79511.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBLi7Fqww2SgBKDgJ9mVpo2aWYadyJ2JMQ',
    appId: '1:159878091400:android:3920078486c2edce7a053d',
    messagingSenderId: '159878091400',
    projectId: 'fir-auth1-79511',
    storageBucket: 'fir-auth1-79511.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD2koZzl4ggIgdj0Hepju1MExk0vz1Tflw',
    appId: '1:159878091400:ios:84f772c172ec192f7a053d',
    messagingSenderId: '159878091400',
    projectId: 'fir-auth1-79511',
    storageBucket: 'fir-auth1-79511.appspot.com',
    androidClientId: '159878091400-i1itjih48tgoohaoo6m5n3gcn9s4ja5n.apps.googleusercontent.com',
    iosClientId: '159878091400-t577apiaqh08g1s429cgr5rql7in61ul.apps.googleusercontent.com',
    iosBundleId: 'com.mafada.firebaseFlutter1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD2koZzl4ggIgdj0Hepju1MExk0vz1Tflw',
    appId: '1:159878091400:ios:84f772c172ec192f7a053d',
    messagingSenderId: '159878091400',
    projectId: 'fir-auth1-79511',
    storageBucket: 'fir-auth1-79511.appspot.com',
    androidClientId: '159878091400-i1itjih48tgoohaoo6m5n3gcn9s4ja5n.apps.googleusercontent.com',
    iosClientId: '159878091400-t577apiaqh08g1s429cgr5rql7in61ul.apps.googleusercontent.com',
    iosBundleId: 'com.mafada.firebaseFlutter1',
  );
}
